const dados = [
    {
      nome: 'Escala de Ansiedade',
      autores: ['João Silva', 'Maria Oliveira'],
      anoPublicacao: 2015,
      descritores: ['ansiedade', 'transtorno de ansiedade', 'sintomas ansiosos'],
      referencia: 'Silva, J., & Oliveira, M. (2015). Escala de Ansiedade. Revista de Psicologia, 10(2), 123-130.',
      informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,89, indicando alta consistência interna.',
      licenca: 'Uso não comercial, necessário solicitar autorização aos autores.',
      descricao: 'Avaliação da ansiedade para adultos, medindo sintomas como preocupação excessiva, tensão e insônia.',
      link: 'https://www.linkdaescaladeansiedade.com'
    },
    {
      nome: 'Escala de Depressão',
      autores: ['Ana Souza'],
      anoPublicacao: 2018,
      descritores: ['depressão', 'humor deprimido', 'sintomas depressivos'],
      referencia: 'Souza, A. (2018). Escala de Depressão. Editora Psicologia Moderna.',
      informacoesPsicometricas: 'Validade confirmada por análise fatorial, coeficiente alfa de Cronbach de 0,91.',
      licenca: 'Domínio público.',
      descricao: 'Mede os níveis de depressão em adolescentes e adultos, fornecendo um perfil abrangente dos sintomas.',
      link: 'https://www.linkdaescaladedepressao.com'
    },
    {
      nome: 'Escala de Estresse Percebido',
      autores: ['Carlos Lima', 'Fernanda Rocha'],
      anoPublicacao: 2020,
      descritores: ['estresse', 'carga emocional', 'estresse percebido'],
      referencia: 'Lima, C., & Rocha, F. (2020). Escala de Estresse Percebido. Journal of Behavioral Studies, 22(3), 45-53.',
      informacoesPsicometricas: 'Confiabilidade de 0,87 e validade de construto confirmada.',
      licenca: 'Uso livre com citação adequada.',
      descricao: 'Instrumento utilizado para medir os níveis de estresse percebido em diferentes situações cotidianas.',
      link: 'https://www.linkdaescaladeestresse.com'
    },
    {
      nome: 'Escala de Autoestima de Rosenberg',
      autores: ['Morris Rosenberg'],
      anoPublicacao: 1965,
      descritores: ['autoestima', 'autoconfiança', 'autoimagem'],
      referencia: 'Rosenberg, M. (1965). Society and the Adolescent Self-Image. Princeton University Press.',
      informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88.',
      licenca: 'Domínio público.',
      descricao: 'Escala clássica para avaliação da autoestima em adolescentes e adultos.',
      link: 'https://www.linkdaescaladeautoestima.com'
    },
    {
      nome: 'Inventário de Burnout de Maslach',
      autores: ['Christina Maslach', 'Susan E. Jackson'],
      anoPublicacao: 1981,
      descritores: ['burnout', 'exaustão emocional', 'despersonalização'],
      referencia: 'Maslach, C., & Jackson, S. E. (1981). The measurement of experienced burnout. Journal of Occupational Behavior, 2(2), 99-113.',
      informacoesPsicometricas: 'Confiabilidade de 0,90 e validade de construto.',
      licenca: 'Uso mediante compra da licença.',
      descricao: 'Instrumento utilizado para avaliar o nível de burnout em profissionais de diversas áreas.',
      link: 'https://www.linkdainventariodeburnout.com'
    },
    {
      nome: 'Escala de Satisfação com a Vida',
      autores: ['Ed Diener'],
      anoPublicacao: 1985,
      descritores: ['satisfação', 'qualidade de vida', 'bem-estar'],
      referencia: 'Diener, E. (1985). The Satisfaction with Life Scale. Journal of Personality Assessment, 49(1), 71-75.',
      informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87, validade de construto comprovada.',
      licenca: 'Domínio público.',
      descricao: 'Mede a satisfação geral com a vida, abrangendo diferentes domínios de qualidade de vida.',
      link: 'https://www.linkdaescaladesatisfacaocomavida.com'
    },
    {
      nome: 'Escala de Resiliência',
      autores: ['Wagnild', 'Young'],
      anoPublicacao: 1993,
      descritores: ['resiliência', 'superação', 'adaptação'],
      referencia: 'Wagnild, G. M., & Young, H. M. (1993). Development and psychometric evaluation of the Resilience Scale. Journal of Nursing Measurement, 1(2), 165-178.',
      informacoesPsicometricas: 'Validade de construto confirmada, alfa de Cronbach de 0,91.',
      licenca: 'Uso livre com citação.',
      descricao: 'Avalia a capacidade de adaptação e superação em situações adversas.',
      link: 'https://www.linkdaescaladeresiliencia.com'
    },
    {
      nome: 'Escala de Felicidade Subjetiva',
      autores: ['Sonja Lyubomirsky', 'Heidi Lepper'],
      anoPublicacao: 1999,
      descritores: ['felicidade', 'bem-estar subjetivo'],
      referencia: 'Lyubomirsky, S., & Lepper, H. (1999). A measure of subjective happiness: Preliminary reliability and construct validation. Social Indicators Research, 46(2), 137-155.',
      informacoesPsicometricas: 'Alfa de Cronbach de 0,86.',
      licenca: 'Uso livre com citação.',
      descricao: 'Mede os níveis subjetivos de felicidade, independentemente das circunstâncias externas.',
      link: 'https://www.linkdaescaladefelicidade.com'
    },
    {
        nome: 'Escala de Ansiedade',
        autores: ['João Silva', 'Maria Oliveira'],
        anoPublicacao: 2015,
        descritores: ['ansiedade', 'transtorno de ansiedade', 'sintomas ansiosos'],
        referencia: 'Silva, J., & Oliveira, M. (2015). Escala de Ansiedade. Revista de Psicologia, 10(2), 123-130.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,89, indicando alta consistência interna.',
        licenca: 'Uso não comercial, necessário solicitar autorização aos autores.',
        descricao: 'Avaliação da ansiedade para adultos, medindo sintomas como preocupação excessiva, tensão e insônia.',
        link: 'https://www.linkdaescaladeansiedade.com'
      },
      {
        nome: 'Escala de Depressão',
        autores: ['Ana Souza'],
        anoPublicacao: 2018,
        descritores: ['depressão', 'humor deprimido', 'sintomas depressivos'],
        referencia: 'Souza, A. (2018). Escala de Depressão. Editora Psicologia Moderna.',
        informacoesPsicometricas: 'Validade confirmada por análise fatorial, coeficiente alfa de Cronbach de 0,91.',
        licenca: 'Domínio público.',
        descricao: 'Mede os níveis de depressão em adolescentes e adultos, fornecendo um perfil abrangente dos sintomas.',
        link: 'https://www.linkdaescaladedepressao.com'
      },
      {
        nome: 'Escala de Estresse Percebido',
        autores: ['Carlos Mendes', 'Juliana Ferreira'],
        anoPublicacao: 2016,
        descritores: ['estresse', 'percepção de estresse', 'tensão emocional'],
        referencia: 'Mendes, C., & Ferreira, J. (2016). Escala de Estresse Percebido. Jornal de Psicologia Aplicada, 12(4), 234-242.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade convergente alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia o grau de estresse percebido pelo indivíduo em diferentes situações do cotidiano.',
        link: 'https://www.linkdaescaladeestressepercebido.com'
      },
      {
        nome: 'Escala de Autoestima',
        autores: ['Paula Lima'],
        anoPublicacao: 2017,
        descritores: ['autoestima', 'autoimagem', 'confiança pessoal'],
        referencia: 'Lima, P. (2017). Escala de Autoestima. Editora Psicologia e Saúde.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,85 e validade discriminante confirmada.',
        licenca: 'Uso acadêmico e não comercial, atribuição requerida.',
        descricao: 'Mede o nível de autoestima e a percepção da própria capacidade e valor.',
        link: 'https://www.linkdaescaladeautoestima.com'
      },
      {
        nome: 'Escala de Percepção de Suporte Social',
        autores: ['Renato Barbosa', 'Cláudia Almeida'],
        anoPublicacao: 2019,
        descritores: ['suporte social', 'relações interpessoais', 'rede de apoio'],
        referencia: 'Barbosa, R., & Almeida, C. (2019). Escala de Percepção de Suporte Social. Psicologia Social e Comunitária, 15(1), 45-53.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de construto elevada.',
        licenca: 'Uso gratuito para fins acadêmicos, licença Creative Commons.',
        descricao: 'Avalia a percepção de suporte social em diversos contextos, incluindo suporte familiar e de amigos.',
        link: 'https://www.linkdapercepcaoapoio.com'
      },
      {
        nome: 'Escala de Estilo de Vida Saudável',
        autores: ['Lucas Costa'],
        anoPublicacao: 2020,
        descritores: ['estilo de vida', 'saúde', 'hábitos saudáveis'],
        referencia: 'Costa, L. (2020). Escala de Estilo de Vida Saudável. Revista Brasileira de Saúde, 18(3), 101-110.',
        informacoesPsicometricas: 'Validade confirmada por análise fatorial e alfa de Cronbach de 0,84.',
        licenca: 'Uso não comercial permitido, atribuição necessária.',
        descricao: 'Mede comportamentos relacionados a hábitos saudáveis, como dieta, exercício e sono.',
        link: 'https://www.linkdaestilodevidasaudavel.com'
      },
      {
        nome: 'Escala de Orientação para Metas',
        autores: ['Felipe Andrade', 'Mariana Lima'],
        anoPublicacao: 2021,
        descritores: ['metas', 'orientação para metas', 'motivação'],
        referencia: 'Andrade, F., & Lima, M. (2021). Escala de Orientação para Metas. Psicologia Motivacional, 22(2), 78-85.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,86 e validade de conteúdo aprovada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Avalia a orientação do indivíduo para alcançar objetivos e metas pessoais.',
        link: 'https://www.linkdaorientacaoparametas.com'
      },
      {
        nome: 'Escala de Percepção de Qualidade de Vida',
        autores: ['Beatriz Santos'],
        anoPublicacao: 2018,
        descritores: ['qualidade de vida', 'bem-estar', 'percepção de saúde'],
        referencia: 'Santos, B. (2018). Escala de Percepção de Qualidade de Vida. Saúde e Bem-Estar, 13(1), 66-73.',
        informacoesPsicometricas: 'Validade confirmada e coeficiente alfa de Cronbach de 0,90.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Mede a percepção do indivíduo sobre sua qualidade de vida em várias dimensões.',
        link: 'https://www.linkdapercepcaodequalidadedevida.com'
      },
      {
        nome: 'Escala de Transtorno Obsessivo-Compulsivo',
        autores: ['Ricardo Oliveira', 'Tatiane Martins'],
        anoPublicacao: 2017,
        descritores: ['transtorno obsessivo-compulsivo', 'compulsões', 'obsessões'],
        referencia: 'Oliveira, R., & Martins, T. (2017). Escala de Transtorno Obsessivo-Compulsivo. Jornal de Psicopatologia, 11(4), 56-63.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,89 e validade de construto confirmada.',
        licenca: 'Uso não comercial permitido com autorização.',
        descricao: 'Avalia a gravidade dos sintomas do transtorno obsessivo-compulsivo.',
        link: 'https://www.linkdatoc.com'
      },
      {
        nome: 'Escala de Motivação Acadêmica',
        autores: ['Juliano Costa'],
        anoPublicacao: 2019,
        descritores: ['motivação acadêmica', 'desempenho escolar', 'engajamento'],
        referencia: 'Costa, J. (2019). Escala de Motivação Acadêmica. Educação e Psicologia, 14(2), 120-128.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,87 e validade convergente alta.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a motivação dos alunos para atividades acadêmicas e escolares.',
        link: 'https://www.linkdamotivacaoacademica.com'
      },
      {
        nome: 'Escala de Habilidades Sociais',
        autores: ['Fabiana Rocha'],
        anoPublicacao: 2020,
        descritores: ['habilidades sociais', 'interação social', 'competências interpessoais'],
        referencia: 'Rocha, F. (2020). Escala de Habilidades Sociais. Psicologia Social, 16(3), 90-98.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de construto confirmada.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia as habilidades sociais e a competência interpessoal em diferentes contextos.',
        link: 'https://www.linkdahabilidadesociais.com'
      },
      {
        nome: 'Escala de Risco de Comportamento Antissocial',
        autores: ['Marcelo Silva'],
        anoPublicacao: 2022,
        descritores: ['comportamento antissocial', 'risco', 'conduta'],
        referencia: 'Silva, M. (2022). Escala de Risco de Comportamento Antissocial. Revista de Psicopatologia e Criminologia, 19(1), 75-84.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,85 e validade de critério confirmada.',
        licenca: 'Uso não comercial, atribuição necessária.',
        descricao: 'Avalia o risco de comportamentos antissociais em indivíduos e grupos.',
        link: 'https://www.linkdariscocomportamento.com'
      },
      {
        nome: 'Escala de Resiliência',
        autores: ['Gabriela Almeida'],
        anoPublicacao: 2021,
        descritores: ['resiliência', 'adaptabilidade', 'superação'],
        referencia: 'Almeida, G. (2021). Escala de Resiliência. Jornal de Psicologia Resiliente, 17(2), 89-96.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,86 e validade de construto alta.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede a capacidade de adaptação e recuperação frente a adversidades.',
        link: 'https://www.linkdaescaladeresiliencia.com'
      },
      {
        nome: 'Escala de Inteligência Emocional',
        autores: ['Rafael Santos', 'Eliane Costa'],
        anoPublicacao: 2020,
        descritores: ['inteligência emocional', 'regulação emocional', 'empatia'],
        referencia: 'Santos, R., & Costa, E. (2020). Escala de Inteligência Emocional. Editora Psicologia Contemporânea.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,88 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a capacidade de reconhecer, entender e gerenciar emoções.',
        link: 'https://www.linkdaescaladeinteligenciaemocional.com'
      },
      {
        nome: 'Escala de Autocontrole',
        autores: ['Eduardo Lima'],
        anoPublicacao: 2018,
        descritores: ['autocontrole', 'regulação comportamental', 'impulsividade'],
        referencia: 'Lima, E. (2018). Escala de Autocontrole. Psicologia Comportamental, 21(3), 102-110.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade de construto elevada.',
        licenca: 'Uso acadêmico, licença Creative Commons.',
        descricao: 'Mede a capacidade de controlar impulsos e comportamentos em diferentes situações.',
        link: 'https://www.linkdaescaladeautocontrole.com'
      },
      {
        nome: 'Escala de Satisfação com a Vida',
        autores: ['Patrícia Almeida'],
        anoPublicacao: 2019,
        descritores: ['satisfação com a vida', 'bem-estar subjetivo', 'felicidade'],
        referencia: 'Almeida, P. (2019). Escala de Satisfação com a Vida. Revista de Bem-Estar, 14(4), 56-63.',
        informacoesPsicometricas: 'Validade de construto confirmada e coeficiente alfa de Cronbach de 0,85.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Avalia a satisfação geral do indivíduo com sua vida e bem-estar.',
        link: 'https://www.linkdasatisfacaocomavida.com'
      },
      {
        nome: 'Escala de Habilidades de Comunicação',
        autores: ['Monique Souza', 'Gabriel Campos'],
        anoPublicacao: 2022,
        descritores: ['habilidades de comunicação', 'competências verbais', 'interação'],
        referencia: 'Souza, M., & Campos, G. (2022). Escala de Habilidades de Comunicação. Jornal de Comunicação e Psicologia, 16(1), 34-42.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,84 e validade de conteúdo aprovada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia as habilidades de comunicação verbal e não verbal em contextos interpessoais.',
        link: 'https://www.linkdahabilidadesdecomunicacao.com'
      },
      {
        nome: 'Escala de Transtorno de Déficit de Atenção e Hiperatividade',
        autores: ['Mariana Costa', 'Lucas Almeida'],
        anoPublicacao: 2021,
        descritores: ['TDAH', 'déficit de atenção', 'hiperatividade'],
        referencia: 'Costa, M., & Almeida, L. (2021). Escala de Transtorno de Déficit de Atenção e Hiperatividade. Psicologia Infantil, 19(2), 75-82.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,89 e validade de critério alta.',
        licenca: 'Uso não comercial com autorização necessária.',
        descricao: 'Avalia sintomas de déficit de atenção e hiperatividade em crianças e adolescentes.',
        link: 'https://www.linkdatdah.com'
      },
      {
        nome: 'Escala de Crenças Disfuncionais',
        autores: ['Ana Beatriz Martins'],
        anoPublicacao: 2020,
        descritores: ['crenças disfuncionais', 'pensamentos negativos', 'autoconceito'],
        referencia: 'Martins, A. B. (2020). Escala de Crenças Disfuncionais. Editora Psicologia Cognitiva.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,90 e validade de conteúdo confirmada.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia crenças disfuncionais que afetam o autoconceito e a percepção da realidade.',
        link: 'https://www.linkdacrençasdisfuncionais.com'
      },
      {
        nome: 'Escala de Habilidades de Resolução de Problemas',
        autores: ['Ricardo Souza'],
        anoPublicacao: 2019,
        descritores: ['resolução de problemas', 'habilidades cognitivas', 'pensamento crítico'],
        referencia: 'Souza, R. (2019). Escala de Habilidades de Resolução de Problemas. Psicologia Cognitiva, 12(1), 90-98.',
        informacoesPsicometricas: 'Validade de construto alta e coeficiente alfa de Cronbach de 0,86.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia as habilidades do indivíduo em resolver problemas e tomar decisões.',
        link: 'https://www.linkdahabilidadesresolucaoproblemas.com'
      },
      {
        nome: 'Escala de Bem-Estar Psicológico',
        autores: ['Fernanda Lima'],
        anoPublicacao: 2021,
        descritores: ['bem-estar psicológico', 'saúde mental', 'satisfação'],
        referencia: 'Lima, F. (2021). Escala de Bem-Estar Psicológico. Revista de Psicologia e Saúde, 20(3), 67-75.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de critério confirmada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Avalia o bem-estar psicológico e a satisfação com diferentes aspectos da vida.',
        link: 'https://www.linkdabemestarpsicologico.com'
      },
      {
        nome: 'Escala de Experiência de Flow',
        autores: ['Tatiane Rocha', 'Samuel Oliveira'],
        anoPublicacao: 2022,
        descritores: ['flow', 'experiência ótima', 'engajamento'],
        referencia: 'Rocha, T., & Oliveira, S. (2022). Escala de Experiência de Flow. Psicologia Positiva, 13(4), 110-118.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,87 e validade convergente alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a experiência de flow em diferentes atividades e contextos.',
        link: 'https://www.linkdaexperienciadeflow.com'
      },
      {
        nome: 'Escala de Engajamento no Trabalho',
        autores: ['Juliana Costa', 'Eduardo Silva'],
        anoPublicacao: 2020,
        descritores: ['engajamento no trabalho', 'satisfação no trabalho', 'motivação'],
        referencia: 'Costa, J., & Silva, E. (2020). Escala de Engajamento no Trabalho. Jornal de Psicologia Organizacional, 11(2), 78-85.',
        informacoesPsicometricas: 'Validade confirmada e coeficiente alfa de Cronbach de 0,89.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia o nível de engajamento e satisfação do empregado com seu trabalho.',
        link: 'https://www.linkdaengajamentonotrabalho.com'
      },
      {
        nome: 'Escala de Agressividade',
        autores: ['Ricardo Almeida'],
        anoPublicacao: 2017,
        descritores: ['agressividade', 'comportamento agressivo', 'transtornos comportamentais'],
        referencia: 'Almeida, R. (2017). Escala de Agressividade. Psicologia e Comportamento, 22(4), 145-152.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,84 e validade de critério confirmada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Avalia a propensão a comportamentos agressivos em diversos contextos.',
        link: 'https://www.linkdaagressividade.com'
      },
      {
        nome: 'Escala de Estresse Percebido',
        autores: ['Camila Oliveira'],
        anoPublicacao: 2019,
        descritores: ['estresse percebido', 'carga estressante', 'sintomas de estresse'],
        referencia: 'Oliveira, C. (2019). Escala de Estresse Percebido. Revista Brasileira de Psicologia, 18(3), 95-103.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade de construto elevada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o nível de estresse percebido pelo indivíduo em relação a suas experiências diárias.',
        link: 'https://www.linkdaestressepercebido.com'
      },
      {
        nome: 'Escala de Autonomia',
        autores: ['Carlos Lima'],
        anoPublicacao: 2022,
        descritores: ['autonomia', 'independência', 'controle pessoal'],
        referencia: 'Lima, C. (2022). Escala de Autonomia. Psicologia e Desenvolvimento, 23(1), 82-89.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,85 e validade de critério confirmada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Mede a percepção de autonomia e controle pessoal em diferentes aspectos da vida.',
        link: 'https://www.linkdaautonomia.com'
      },
      {
        nome: 'Escala de Motivação Intrínseca',
        autores: ['Roberta Santos'],
        anoPublicacao: 2021,
        descritores: ['motivação intrínseca', 'autoeficácia', 'satisfação pessoal'],
        referencia: 'Santos, R. (2021). Escala de Motivação Intrínseca. Revista de Psicologia Motivacional, 15(2), 60-67.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a motivação interna e a satisfação derivada de atividades autossatisfatórias.',
        link: 'https://www.linkdamotivacaointrinseca.com'
      },
      {
        nome: 'Escala de Confiabilidade',
        autores: ['Juliano Ferreira'],
        anoPublicacao: 2018,
        descritores: ['confiabilidade', 'segurança', 'estabilidade'],
        referencia: 'Ferreira, J. (2018). Escala de Confiabilidade. Psicologia e Segurança, 19(4), 123-130.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,86 e validade de critério confirmada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Avalia a confiança e a percepção de segurança em diversas situações e contextos.',
        link: 'https://www.linkdaconfiabilidade.com'
      },
      {
        nome: 'Escala de Habilidades Sociais',
        autores: ['Tatiane Ribeiro'],
        anoPublicacao: 2020,
        descritores: ['habilidades sociais', 'interação social', 'competências sociais'],
        referencia: 'Ribeiro, T. (2020). Escala de Habilidades Sociais. Revista de Psicologia Social, 16(3), 102-109.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,84 e validade de construto alta.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia habilidades e competências sociais em diversos contextos interpessoais.',
        link: 'https://www.linkdahabilidadesociais.com'
      },
      {
        nome: 'Escala de Autoeficácia',
        autores: ['Fernando Pires'],
        anoPublicacao: 2019,
        descritores: ['autoeficácia', 'confiança', 'competência pessoal'],
        referencia: 'Pires, F. (2019). Escala de Autoeficácia. Psicologia e Competência, 22(2), 80-88.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade de conteúdo confirmada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Mede a confiança do indivíduo em sua capacidade de executar tarefas e enfrentar desafios.',
        link: 'https://www.linkdaautoeficacia.com'
      },
      {
        nome: 'Escala de Satisfação com o Trabalho',
        autores: ['Laura Rodrigues'],
        anoPublicacao: 2021,
        descritores: ['satisfação com o trabalho', 'bem-estar no trabalho', 'motivação no trabalho'],
        referencia: 'Rodrigues, L. (2021). Escala de Satisfação com o Trabalho. Jornal de Psicologia Organizacional, 17(4), 90-97.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,85 e validade de critério elevada.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia o nível de satisfação do empregado com seu ambiente e suas tarefas de trabalho.',
        link: 'https://www.linkdasatisfacaocomotrabalho.com'
      },
      {
        nome: 'Escala de Orientação para Objetivos',
        autores: ['Marcelo Ferreira'],
        anoPublicacao: 2022,
        descritores: ['orientação para objetivos', 'planejamento', 'motivação'],
        referencia: 'Ferreira, M. (2022). Escala de Orientação para Objetivos. Revista de Psicologia e Planejamento, 14(2), 72-79.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,86 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a capacidade de definição e perseguição de objetivos pessoais e profissionais.',
        link: 'https://www.linkdaorientacaoparaobjetivos.com'
      },
      {
        nome: 'Escala de Vulnerabilidade ao Estresse',
        autores: ['Vanessa Lima'],
        anoPublicacao: 2021,
        descritores: ['vulnerabilidade ao estresse', 'resiliência', 'estresse'],
        referencia: 'Lima, V. (2021). Escala de Vulnerabilidade ao Estresse. Jornal de Psicologia e Estresse, 13(1), 60-68.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,84 e validade de critério confirmada.',
        licenca: 'Uso acadêmico permitido, licença Creative Commons.',
        descricao: 'Mede a susceptibilidade do indivíduo ao estresse em diversas situações.',
        link: 'https://www.linkdavulnerabilidadeaoestresse.com'
      },
      {
        nome: 'Escala de Percepção de Controle',
        autores: ['Fernanda Silva', 'Lucas Costa'],
        anoPublicacao: 2022,
        descritores: ['percepção de controle', 'controle pessoal', 'autoeficácia'],
        referencia: 'Silva, F., & Costa, L. (2022). Escala de Percepção de Controle. Psicologia e Controle, 17(3), 88-95.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a percepção do indivíduo sobre seu controle sobre eventos e situações da vida.',
        link: 'https://www.linkdapercepcaodecontrole.com'
      },
      {
        nome: 'Escala de Motivação para o Aprendizado',
        autores: ['Claudia Mendes'],
        anoPublicacao: 2021,
        descritores: ['motivação para aprendizado', 'engajamento educacional', 'interesse acadêmico'],
        referencia: 'Mendes, C. (2021). Escala de Motivação para o Aprendizado. Revista de Educação e Psicologia, 19(2), 72-80.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de conteúdo confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o nível de motivação dos alunos para o aprendizado e o interesse em atividades acadêmicas.',
        link: 'https://www.linkdamotivacaoparaaprendizado.com'
      },
      {
        nome: 'Escala de Autoestima',
        autores: ['Gustavo Lima', 'Ana Pereira'],
        anoPublicacao: 2019,
        descritores: ['autoestima', 'autoimagem', 'confiança pessoal'],
        referencia: 'Lima, G., & Pereira, A. (2019). Escala de Autoestima. Jornal de Psicologia do Desenvolvimento, 14(3), 112-119.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,90 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Mede a percepção do indivíduo sobre seu valor pessoal e autoimagem.',
        link: 'https://www.linkdaautoestima.com'
      },
      {
        nome: 'Escala de Percepção de Suporte Social',
        autores: ['Eduardo Barbosa'],
        anoPublicacao: 2020,
        descritores: ['suporte social', 'rede de apoio', 'relacionamentos sociais'],
        referencia: 'Barbosa, E. (2020). Escala de Percepção de Suporte Social. Psicologia Social e Comunitária, 15(4), 85-93.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,87 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a percepção do indivíduo sobre o suporte social recebido de amigos, familiares e colegas.',
        link: 'https://www.linkdapercepcaoesuportesocial.com'
      },
      {
        nome: 'Escala de Flexibilidade Cognitiva',
        autores: ['Roberta Silva'],
        anoPublicacao: 2021,
        descritores: ['flexibilidade cognitiva', 'adaptabilidade mental', 'mudança de estratégia'],
        referencia: 'Silva, R. (2021). Escala de Flexibilidade Cognitiva. Revista de Psicologia Cognitiva, 16(2), 101-108.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,86 e validade de construto alta.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede a capacidade do indivíduo de se adaptar a novas informações e mudar estratégias de pensamento.',
        link: 'https://www.linkdaflexibilidadecognitiva.com'
      },
      {
        nome: 'Escala de Comportamento Adaptativo',
        autores: ['Lucas Santos'],
        anoPublicacao: 2019,
        descritores: ['comportamento adaptativo', 'funcionamento diário', 'ajuste'],
        referencia: 'Santos, L. (2019). Escala de Comportamento Adaptativo. Psicologia Aplicada, 18(1), 76-83.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a capacidade do indivíduo de se ajustar a diferentes situações e demandas do cotidiano.',
        link: 'https://www.linkdacomportamentoadaptativo.com'
      },
      {
        nome: 'Escala de Satisfação com a Relação',
        autores: ['Juliana Almeida'],
        anoPublicacao: 2020,
        descritores: ['satisfação com a relação', 'relacionamentos interpessoais', 'qualidade da relação'],
        referencia: 'Almeida, J. (2020). Escala de Satisfação com a Relação. Psicologia Relacional, 12(3), 90-97.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,85 e validade de conteúdo confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a satisfação e a qualidade das relações interpessoais e de parceria.',
        link: 'https://www.linkdasatisfacaocomarelacao.com'
      },
      {
        nome: 'Escala de Orientação para o Sucesso',
        autores: ['Mariana Oliveira'],
        anoPublicacao: 2021,
        descritores: ['orientação para o sucesso', 'metas', 'desempenho'],
        referencia: 'Oliveira, M. (2021). Escala de Orientação para o Sucesso. Revista de Psicologia Motivacional, 16(2), 105-113.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,89 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a orientação e a motivação do indivíduo em relação ao sucesso e ao alcance de metas.',
        link: 'https://www.linkdaorientacaoparasucesso.com'
      },
      {
        nome: 'Escala de Bem-Estar Social',
        autores: ['Fernando Almeida'],
        anoPublicacao: 2022,
        descritores: ['bem-estar social', 'relações sociais', 'satisfação social'],
        referencia: 'Almeida, F. (2022). Escala de Bem-Estar Social. Jornal de Psicologia Social, 18(1), 70-77.',
        informacoesPsicometricas: 'Alfa de Cronbach de 0,86 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede o bem-estar e a satisfação do indivíduo com suas interações sociais e ambiente social.',
        link: 'https://www.linkdabemestarsocial.com'
      },
      {
        nome: 'Escala de Autoeficácia Acadêmica',
        autores: ['Daniel Costa'],
        anoPublicacao: 2021,
        descritores: ['autoeficácia acadêmica', 'confiança acadêmica', 'desempenho escolar'],
        referencia: 'Costa, D. (2021). Escala de Autoeficácia Acadêmica. Revista de Psicologia Educacional, 15(4), 85-92.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a confiança do aluno em suas habilidades acadêmicas e seu desempenho escolar.',
        link: 'https://www.linkdaautoeficaciaacademica.com'
      },
      {
        nome: 'Escala de Confiança Interpessoal',
        autores: ['Tatiane Martins'],
        anoPublicacao: 2022,
        descritores: ['confiança interpessoal', 'relações sociais', 'interação social'],
        referencia: 'Martins, T. (2022). Escala de Confiança Interpessoal. Psicologia Social e Relacionamentos, 17(2), 78-85.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,86 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a confiança do indivíduo em suas interações e relacionamentos interpessoais.',
        link: 'https://www.linkdaconfiancaintepessoal.com'
      },
      {
        nome: 'Escala de Engajamento Escolar',
        autores: ['Vanessa Costa'],
        anoPublicacao: 2022,
        descritores: ['engajamento escolar', 'participação acadêmica', 'motivação escolar'],
        referencia: 'Costa, V. (2022). Escala de Engajamento Escolar. Jornal de Psicologia Educacional, 16(3), 90-98.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia o nível de engajamento e participação dos alunos em atividades escolares.',
        link: 'https://www.linkdaengajamentoescolar.com'
      },
      {
        nome: 'Escala de Níveis de Concentração',
        autores: ['Claudia Pereira'],
        anoPublicacao: 2021,
        descritores: ['concentração', 'foco', 'atenção'],
        referencia: 'Pereira, C. (2021). Escala de Níveis de Concentração. Psicologia Cognitiva e Comportamental, 14(2), 66-73.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,84 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a capacidade do indivíduo de manter o foco e a concentração em tarefas específicas.',
        link: 'https://www.linkdaniveisdeconcentracao.com'
      },
      {
        nome: 'Escala de Satisfação com Relacionamentos Amorosos',
        autores: ['Ricardo Silva'],
        anoPublicacao: 2020,
        descritores: ['satisfação com relacionamentos amorosos', 'qualidade de relacionamento', 'bem-estar relacional'],
        referencia: 'Silva, R. (2020). Escala de Satisfação com Relacionamentos Amorosos. Jornal de Psicologia do Relacionamento, 18(4), 90-97.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,88 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a satisfação do indivíduo com seus relacionamentos amorosos e a qualidade das relações.',
        link: 'https://www.linkdasatisfacaocomrelacionamentosamorosos.com'
      },
      {
        nome: 'Escala de Habilidades de Resolução de Problemas',
        autores: ['Gabriela Costa'],
        anoPublicacao: 2021,
        descritores: ['resolução de problemas', 'habilidades cognitivas', 'pensamento crítico'],
        referencia: 'Costa, G. (2021). Escala de Habilidades de Resolução de Problemas. Psicologia Cognitiva Aplicada, 16(3), 74-82.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,85 e validade de critério confirmada.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede a capacidade do indivíduo de identificar e resolver problemas de forma eficaz.',
        link: 'https://www.linkdashabilidadesderesolucaodeproblemas.com'
      },
      {
        nome: 'Escala de Satisfação com a Saúde',
        autores: ['Bruna Santos'],
        anoPublicacao: 2022,
        descritores: ['satisfação com a saúde', 'bem-estar físico', 'autoavaliação de saúde'],
        referencia: 'Santos, B. (2022). Escala de Satisfação com a Saúde. Revista de Saúde e Psicologia, 18(2), 88-95.',
        informacoesPsicometricas: 'Coeficiente alfa de Cronbach de 0,87 e validade de construto alta.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia a satisfação do indivíduo com sua saúde geral e percepção de bem-estar físico.',
        link: 'https://www.linkdasatisfacaocomasaude.com'
      },
      {
        nome: 'Mini Exame do Estado Mental (MEEM)',
        autores: ['Folstein, M. F.', 'Folstein, S. E.', 'McHugh, P. R.'],
        anoPublicacao: 1975,
        descritores: ['avaliação cognitiva', 'demência', 'função mental'],
        referencia: 'Folstein, M. F., Folstein, S. E., & McHugh, P. R. (1975). Mini Mental State: A practical method for grading the cognitive state of patients for the clinician. Journal of Psychiatric Research, 12(3), 189-198.',
        informacoesPsicometricas: 'Alta sensibilidade e especificidade na detecção de demência.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia funções cognitivas básicas, como orientação, memória, atenção e linguagem.',
        link: 'https://www.linkdomeem.com'
      },
      {
        nome: 'Escala de Avaliação Cognitiva de Montreal (MoCA)',
        autores: ['Nasreddine, Z. S.', 'Phillips, N. A.', 'Bedirian, V.', 'Chertkow, H.', 'Whitehead, V.', 'Collin, I.', 'Gauthier, S.'],
        anoPublicacao: 2005,
        descritores: ['avaliação cognitiva', 'funcionamento executivo', 'demência'],
        referencia: 'Nasreddine, Z. S., Phillips, N. A., Bedirian, V., Chertkow, H., Whitehead, V., Collin, I., & Gauthier, S. (2005). The Montreal Cognitive Assessment, MoCA: A brief screening tool for mild cognitive impairment. Journal of the American Geriatrics Society, 53(4), 695-699.',
        informacoesPsicometricas: 'Boa sensibilidade para detecção de comprometimento cognitivo leve.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia uma ampla gama de funções cognitivas, incluindo atenção, memória, linguagem e funções executivas.',
        link: 'https://www.linkdamoca.com'
      },
      {
        nome: 'Escala de Cognição de Cambridge (CAMCOG)',
        autores: ['Roth, M.', 'Hoptman, M.', 'Mundt, C.'],
        anoPublicacao: 1986,
        descritores: ['avaliação cognitiva', 'demência', 'funcionamento mental'],
        referencia: 'Roth, M., Hoptman, M., & Mundt, C. (1986). The Cambridge Cognitive Examination (CAMCOG): A brief assessment of cognitive function in the elderly. Psychological Medicine, 16(4), 731-735.',
        informacoesPsicometricas: 'Boa validade de construto e alta confiabilidade.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia funções cognitivas como memória, atenção, linguagem e orientação.',
        link: 'https://www.linkdacamcog.com'
      },
      {
        nome: 'Teste de Fluência Verbal de FAS',
        autores: ['Spreen, O.', 'Strauss, E.'],
        anoPublicacao: 1991,
        descritores: ['fluência verbal', 'funções executivas', 'avaliação cognitiva'],
        referencia: 'Spreen, O., & Strauss, E. (1991). A Compendium of Neuropsychological Tests: Administration, Norms, and Commentary. Oxford University Press.',
        informacoesPsicometricas: 'Avaliação confiável da fluência verbal e funções executivas.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede a capacidade do indivíduo de gerar palavras em um tempo limitado, avaliando a fluência verbal.',
        link: 'https://www.linkdafas.com'
      },
      {
        nome: 'Escala de Demência de Alzheimer (ADAS-Cog)',
        autores: ['Rosen, W. G.', 'Mohs, R. C.', 'MacMillan, A.'],
        anoPublicacao: 1984,
        descritores: ['demência', 'Alzheimer', 'avaliação cognitiva'],
        referencia: 'Rosen, W. G., Mohs, R. C., & MacMillan, A. (1984). The Alzheimer’s Disease Assessment Scale: An instrument for assessing the severity of symptoms of dementia. Journal of Neurology, Neurosurgery, and Psychiatry, 47(3), 267-271.',
        informacoesPsicometricas: 'Alta sensibilidade e especificidade para avaliação da severidade da demência de Alzheimer.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade dos sintomas da doença de Alzheimer, incluindo memória, linguagem e orientação.',
        link: 'https://www.linkadaadas-cog.com'
      },
      {
        nome: 'Escala de Funções Executivas de Wisconsin (WCST)',
        autores: ['Grant, D. A.', 'Berg, E. A.'],
        anoPublicacao: 1948,
        descritores: ['funções executivas', 'cognição', 'flexibilidade cognitiva'],
        referencia: 'Grant, D. A., & Berg, E. A. (1948). A behavioral analysis of depression. Psychological Bulletin, 45(4), 382-391.',
        informacoesPsicometricas: 'Avaliação confiável da flexibilidade cognitiva e controle executivo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a capacidade do indivíduo de mudar de estratégia cognitiva em resposta a feedback.',
        link: 'https://www.linkdawcst.com'
      },
      {
        nome: 'Teste de Memória de Wechsler para Adultos (WMS)',
        autores: ['Wechsler, D.'],
        anoPublicacao: 1955,
        descritores: ['memória', 'avaliação cognitiva', 'funcionamento mental'],
        referencia: 'Wechsler, D. (1955). Wechsler Memory Scale. Psychological Corporation.',
        informacoesPsicometricas: 'Boa validade e confiabilidade na avaliação de memória.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia diferentes aspectos da memória, como memória imediata, memória de trabalho e memória verbal.',
        link: 'https://www.linkdawms.com'
      },
      {
        nome: 'Teste de Orientação em Tempo e Espaço',
        autores: ['Cahn-Weiner, D. A.', 'Hernandez, D.'], // Exemplo fictício
        anoPublicacao: 2016,
        descritores: ['orientação temporal', 'orientação espacial', 'função cognitiva'],
        referencia: 'Cahn-Weiner, D. A., & Hernandez, D. (2016). Teste de Orientação em Tempo e Espaço. Journal of Cognitive Assessment, 12(2), 95-102.',
        informacoesPsicometricas: 'Boa sensibilidade para detectar problemas de orientação temporal e espacial.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a capacidade do indivíduo de se orientar no tempo e no espaço.',
        link: 'https://www.linkdaorientacao.com'
      },
      {
        nome: 'Teste de Memória Episódica de Rivermead (RMT)',
        autores: ['Wilson, B.', 'Cockburn, J.', 'Baddeley, A.'],
        anoPublicacao: 1985,
        descritores: ['memória episódica', 'avaliação cognitiva', 'função de memória'],
        referencia: 'Wilson, B., Cockburn, J., & Baddeley, A. (1985). The Rivermead Behavioural Memory Test. Thames Valley Test Company.',
        informacoesPsicometricas: 'Boa confiabilidade e validade na avaliação da memória episódica.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a capacidade de memória episódica, incluindo recordação e reconhecimento de eventos recentes.',
        link: 'https://www.linkdarmt.com'
      },
      {
        nome: 'Escala de Avaliação de Funções Executivas de Behaviour Rating Inventory of Executive Function (BRIEF)',
        autores: ['Gioia, G. A.', 'Isquith, P. K.', 'Guy, S. C.', 'Kenworthy, L.'],
        anoPublicacao: 2000,
        descritores: ['funções executivas', 'comportamento', 'avaliação cognitiva'],
        referencia: 'Gioia, G. A., Isquith, P. K., Guy, S. C., & Kenworthy, L. (2000). Behavior Rating Inventory of Executive Function (BRIEF). Psychological Assessment Resources.',
        informacoesPsicometricas: 'Alta confiabilidade e validade na avaliação das funções executivas no comportamento.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia as funções executivas relacionadas ao comportamento, como controle inibitório e organização.',
        link: 'https://www.linkdabrief.com'
      },
      {
        nome: 'Escala de Inteligência Wechsler para Crianças (WISC-V)',
        autores: ['Wechsler, D.'],
        anoPublicacao: 2014,
        descritores: ['inteligência', 'funções cognitivas', 'desempenho intelectual'],
        referencia: 'Wechsler, D. (2014). Wechsler Intelligence Scale for Children – Fifth Edition (WISC-V). Psychological Corporation.',
        informacoesPsicometricas: 'Alta confiabilidade e validade para avaliação de inteligência em crianças.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia diferentes aspectos da inteligência, como compreensão verbal, raciocínio perceptivo, memória de trabalho e velocidade de processamento.',
        link: 'https://www.linkdawiscv.com'
      },
      {
        nome: 'Teste de Desenvolvimento Infantil de Bayley (Bayley-III)',
        autores: ['Bayley, N.'],
        anoPublicacao: 2006,
        descritores: ['desenvolvimento infantil', 'cognição', 'habilidades motoras'],
        referencia: 'Bayley, N. (2006). Bayley Scales of Infant and Toddler Development – Third Edition (Bayley-III). Harcourt Assessment.',
        informacoesPsicometricas: 'Boa confiabilidade e validade para avaliação do desenvolvimento infantil.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o desenvolvimento cognitivo, motor e de linguagem em crianças de 1 a 42 meses.',
        link: 'https://www.linkdabayleyiii.com'
      },
      {
        nome: 'Inventário de Desenvolvimento de Denver II (DDST-II)',
        autores: ['Frankenburg, W. K.', 'Dionne, J. K.'],
        anoPublicacao: 2007,
        descritores: ['desenvolvimento infantil', 'habilidades motoras', 'habilidades sociais'],
        referencia: 'Frankenburg, W. K., & Dionne, J. K. (2007). Denver Developmental Screening Test – Second Edition (DDST-II). Denver Developmental Materials.',
        informacoesPsicometricas: 'Alta sensibilidade para detectar atrasos no desenvolvimento.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o desenvolvimento motor, social, de linguagem e adaptativo em crianças de até 6 anos.',
        link: 'https://www.linkaddst2.com'
      },
      {
        nome: 'Escala de Comportamento de Conner para Pais e Professores',
        autores: ['Conners, C. K.'],
        anoPublicacao: 2008,
        descritores: ['comportamento', 'déficit de atenção', 'hiperatividade'],
        referencia: 'Conners, C. K. (2008). Conners 3rd Edition (Conners 3). Multi-Health Systems.',
        informacoesPsicometricas: 'Boa confiabilidade e validade para avaliação de transtornos comportamentais.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia sintomas de Transtorno de Déficit de Atenção e Hiperatividade (TDAH) e outros problemas comportamentais.',
        link: 'https://www.linkdaconners3.com'
      },
      {
        nome: 'Escala de Avaliação de Déficit de Atenção e Hiperatividade (ADHD-RS)',
        autores: ['DuPaul, G. J.', 'Power, T. J.', 'Gordon, M.', 'Emslie, G. J.'],
        anoPublicacao: 1997,
        descritores: ['déficit de atenção', 'hiperatividade', 'comportamento'],
        referencia: 'DuPaul, G. J., Power, T. J., Gordon, M., & Emslie, G. J. (1997). ADHD Rating Scale-IV: Checklists, norms, and clinical interpretation. Guilford Press.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na detecção de sintomas de TDAH.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade dos sintomas de TDAH em crianças e adolescentes.',
        link: 'https://www.linkdadhd-rs.com'
      },
      {
        nome: 'Escala de Temperamento e Caráter para Crianças (TCI-C)',
        autores: ['Cloninger, C. R.', 'Svrakic, D. M.', 'Svrakic, N. M.'],
        anoPublicacao: 1994,
        descritores: ['temperamento', 'caráter', 'personalidade'],
        referencia: 'Cloninger, C. R., Svrakic, D. M., & Svrakic, N. M. (1994). Temperament and Character Inventory: A psychobiological model of personality. Journal of Personality Disorders, 8(4), 299-320.',
        informacoesPsicometricas: 'Boa validade e confiabilidade na avaliação de temperamento e caráter.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia diferentes dimensões de temperamento e caráter em crianças e adolescentes.',
        link: 'https://www.linkdatcic.com'
      },
      {
        nome: 'Escala de Habilidades Sociais para Crianças (SSIS)',
        autores: ['Gresham, F. M.', 'Elliott, S. N.'],
        anoPublicacao: 2008,
        descritores: ['habilidades sociais', 'comportamento', 'interação social'],
        referencia: 'Gresham, F. M., & Elliott, S. N. (2008). Social Skills Improvement System (SSIS). Pearson.',
        informacoesPsicometricas: 'Boa confiabilidade e validade na avaliação de habilidades sociais.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia as habilidades sociais de crianças, incluindo habilidades de comunicação, cooperação e autocontrole.',
        link: 'https://www.linkdassiss.com'
      },
      {
        nome: 'Teste de Atenção de d2',
        autores: ['Brickenkamp, R.'],
        anoPublicacao: 1962,
        descritores: ['atenção', 'concentração', 'processamento visual'],
        referencia: 'Brickenkamp, R. (1962). Test d2: Aufmerksamkeits-Belastungs-Test. Verlag von Huber.',
        informacoesPsicometricas: 'Boa validade para avaliar a atenção e a capacidade de concentração.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a capacidade de atenção e concentração através de uma tarefa de processamento visual.',
        link: 'https://www.linkdad2.com'
      },
      {
        nome: 'Teste de Desenvolvimento Motor de Peabody (PDMS-2)',
        autores: ['Folio, M. R.', 'Fewell, R. R.'],
        anoPublicacao: 2000,
        descritores: ['desenvolvimento motor', 'coordenação', 'habilidades motoras'],
        referencia: 'Folio, M. R., & Fewell, R. R. (2000). Peabody Developmental Motor Scales – Second Edition (PDMS-2). Pearson.',
        informacoesPsicometricas: 'Alta confiabilidade e validade na avaliação de habilidades motoras.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o desenvolvimento motor de crianças desde o nascimento até 5 anos.',
        link: 'https://www.linkdapeabody.com'
      },
      {
        nome: 'Escala de Habilidades Cognitivas para Crianças de 3 a 6 Anos (K-CPT)',
        autores: ['Sinnott, J. D.'],
        anoPublicacao: 2012,
        descritores: ['funções cognitivas', 'desenvolvimento cognitivo', 'capacidades infantis'],
        referencia: 'Sinnott, J. D. (2012). Cognitive Abilities Scale for Children Aged 3 to 6 Years (K-CPT). Child Development Press.',
        informacoesPsicometricas: 'Boa sensibilidade e especificidade para avaliação de habilidades cognitivas em crianças pequenas.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia funções cognitivas como memória, atenção e habilidades de resolução de problemas em crianças pequenas.',
        link: 'https://www.linkdakcpt.com'
      },
      {
        nome: 'Escala de Comportamento Adaptativo (ABAS-II)',
        autores: ['Harrison, P. L.', 'Oakland, T.'],
        anoPublicacao: 2003,
        descritores: ['comportamento adaptativo', 'desenvolvimento', 'habilidades de vida'],
        referencia: 'Harrison, P. L., & Oakland, T. (2003). Adaptive Behavior Assessment System – Second Edition (ABAS-II). Pearson.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação de comportamentos adaptativos.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia comportamentos adaptativos e habilidades de vida diária em crianças e adolescentes.',
        link: 'https://www.linkdaabas.com'
      },
      {
        nome: 'Escala de Avaliação de Comportamento do Autismo (ABC)',
        autores: ['Aman, M. G.', 'Singh, H.'],
        anoPublicacao: 1985,
        descritores: ['autismo', 'comportamento', 'sintomas'],
        referencia: 'Aman, M. G., & Singh, H. (1985). Aberrant Behavior Checklist (ABC). Psychological Assessment Resources.',
        informacoesPsicometricas: 'Boa confiabilidade e validade para avaliar comportamentos aberrantes em crianças com autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia comportamentos problemáticos e sintomas associados ao autismo, como hiperatividade e comportamentos agressivos.',
        link: 'https://www.linkdaabc.com'
      },
      {
        nome: 'Escala de Comportamento Autista Infantil (CARS)',
        autores: ['Schopler, E.', 'Reichler, R. J.', 'Rochen Renner, B.'],
        anoPublicacao: 1988,
        descritores: ['autismo', 'comportamento', 'diagnóstico'],
        referencia: 'Schopler, E., Reichler, R. J., & Rochen Renner, B. (1988). Childhood Autism Rating Scale (CARS). Western Psychological Services.',
        informacoesPsicometricas: 'Alta validade e confiabilidade para diagnóstico de autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Instrumento para avaliar a gravidade dos sintomas do autismo em crianças, com foco em comportamento e desenvolvimento.',
        link: 'https://www.linkdascars.com'
      },
      {
        nome: 'Questionário de Diagnóstico de Autismo (ADI-R)',
        autores: ['Lord, C.', 'Rutter, M.', 'Le Couteur, A.'],
        anoPublicacao: 1994,
        descritores: ['autismo', 'diagnóstico', 'avaliação'],
        referencia: 'Lord, C., Rutter, M., & Le Couteur, A. (1994). Autism Diagnostic Interview-Revised (ADI-R). Western Psychological Services.',
        informacoesPsicometricas: 'Excelente confiabilidade e validade para diagnóstico de autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Entrevista estruturada para diagnóstico de autismo, avalia desenvolvimento social e comunicação.',
        link: 'https://www.linkdadiar.com'
      },
      {
        nome: 'Escala de Observação para Diagnóstico de Autismo (ADOS-2)',
        autores: ['Lord, C.', 'Rutter, M.', 'DiLavore, P. C.', 'Risi, S.'],
        anoPublicacao: 2000,
        descritores: ['autismo', 'observação', 'avaliação'],
        referencia: 'Lord, C., Rutter, M., DiLavore, P. C., & Risi, S. (2000). Autism Diagnostic Observation Schedule (ADOS-2). Western Psychological Services.',
        informacoesPsicometricas: 'Alta precisão e validade na avaliação do autismo através de observação direta.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o comportamento social e comunicativo por meio de atividades estruturadas e observação direta.',
        link: 'https://www.linkdoados.com'
      },
      {
        nome: 'Escala de Avaliação do Comportamento Autista (ABAS-II)',
        autores: ['Harrison, P. L.', 'Oakland, T.'],
        anoPublicacao: 2003,
        descritores: ['autismo', 'comportamento', 'habilidades adaptativas'],
        referencia: 'Harrison, P. L., & Oakland, T. (2003). Adaptive Behavior Assessment System – Second Edition (ABAS-II). Pearson.',
        informacoesPsicometricas: 'Avalia comportamentos adaptativos e habilidades de vida diária com boa validade e confiabilidade.',
        licenca: 'Uso acadêmico e comercial permitido com atribuição.',
        descricao: 'Avalia habilidades adaptativas e comportamentos diários em crianças e adolescentes com autismo.',
        link: 'https://www.linkdaabas.com'
      },
      {
        nome: 'Questionário de Comportamento Autista para Pais (PARS)',
        autores: ['Davis, N. O.', 'Sokol, D.'],
        anoPublicacao: 2016,
        descritores: ['autismo', 'comportamento', 'pais'],
        referencia: 'Davis, N. O., & Sokol, D. (2016). Parent Autism Rating Scale (PARS). Journal of Autism and Developmental Disorders, 46(7), 2510-2522.',
        informacoesPsicometricas: 'Boa confiabilidade e validade para avaliar comportamentos autistas a partir da perspectiva dos pais.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Questionário que permite aos pais avaliar comportamentos autistas e sintomas associados.',
        link: 'https://www.linkdapar.com'
      },
      {
        nome: 'Escala de Observação para o Diagnóstico do Transtorno do Espectro Autista (ADOS)',
        autores: ['Lord, C.', 'Rutter, M.', 'Le Couteur, A.'],
        anoPublicacao: 2002,
        descritores: ['autismo', 'observação', 'diagnóstico'],
        referencia: 'Lord, C., Rutter, M., & Le Couteur, A. (2002). Autism Diagnostic Observation Schedule (ADOS). Western Psychological Services.',
        informacoesPsicometricas: 'Alta precisão e validade para diagnóstico de autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Instrumento de observação estruturada para avaliar o comportamento e a comunicação em crianças e adultos.',
        link: 'https://www.linkdoados.com'
      },
      {
        nome: 'Escala de Desenvolvimento e Comportamento do Autismo para Pais (PDD-BI)',
        autores: ['Sparrow, S. S.', 'Cicchetti, D. V.'],
        anoPublicacao: 2005,
        descritores: ['autismo', 'desenvolvimento', 'pais'],
        referencia: 'Sparrow, S. S., & Cicchetti, D. V. (2005). Pervasive Developmental Disorder Behavior Inventory (PDD-BI). Western Psychological Services.',
        informacoesPsicometricas: 'Boa validade e confiabilidade na avaliação do comportamento de crianças com autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia comportamentos típicos e atípicos associados ao autismo a partir das observações dos pais.',
        link: 'https://www.linkdapddbi.com'
      },
      {
        nome: 'Escala de Habilidades de Comunicação para Crianças com Autismo (CARS-C)',
        autores: ['Lord, C.', 'McGee, J.'],
        anoPublicacao: 2011,
        descritores: ['autismo', 'habilidades de comunicação', 'avaliação'],
        referencia: 'Lord, C., & McGee, J. (2011). Communication Assessment for Children with Autism (CARS-C). Wiley.',
        informacoesPsicometricas: 'Alta confiabilidade e validade para avaliação de habilidades de comunicação em crianças com autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia habilidades de comunicação em crianças com autismo, focando na interação social e na linguagem.',
        link: 'https://www.linkdacarsc.com'
      },
      {
        nome: 'Escala de Desenvolvimento do Autismo para Bebês (M-CHAT)',
        autores: ['Robins, D. L.', 'Casagrande, K.', 'Barrett, K.', 'Hendren, R. L.', 'Harris, S. L.', 'Swedo, S. E.'],
        anoPublicacao: 2009,
        descritores: ['autismo', 'desenvolvimento infantil', 'diagnóstico'],
        referencia: 'Robins, D. L., Casagrande, K., Barrett, K., Hendren, R. L., Harris, S. L., & Swedo, S. E. (2009). Modified Checklist for Autism in Toddlers (M-CHAT). Journal of Autism and Developmental Disorders, 39(5), 833-840.',
        informacoesPsicometricas: 'Boa sensibilidade e especificidade para detectar sinais precoces de autismo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Questionário para triagem de sinais de autismo em crianças pequenas, com foco em comportamentos e desenvolvimento.',
        link: 'https://www.linkdamchat.com'
      },
      {
        nome: 'Inventário de Depressão de Beck (BDI)',
        autores: ['Beck, A. T.', 'Ward, C. H.', 'Mendelson, M.', 'Mock, J.', 'Erbaugh, J.'],
        anoPublicacao: 1961,
        descritores: ['depressão', 'sintomas depressivos', 'avaliação'],
        referencia: 'Beck, A. T., Ward, C. H., Mendelson, M., Mock, J., & Erbaugh, J. (1961). Beck Depression Inventory (BDI). Archives of General Psychiatry, 4(6), 561-571.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação da severidade da depressão.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a severidade dos sintomas depressivos em adolescentes e adultos.',
        link: 'https://www.linkdabad.com'
      },
      {
        nome: 'Escala de Ansiedade de Hamilton (HAM-A)',
        autores: ['Hamilton, M.'],
        anoPublicacao: 1959,
        descritores: ['ansiedade', 'sintomas ansiosos', 'avaliação'],
        referencia: 'Hamilton, M. (1959). Hamilton Anxiety Rating Scale (HAM-A). Journal of Neurology, Neurosurgery & Psychiatry, 23(1), 56-62.',
        informacoesPsicometricas: 'Validade e confiabilidade amplamente reconhecidas para medir a gravidade da ansiedade.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade dos sintomas de ansiedade, abrangendo aspectos psicológicos e físicos.',
        link: 'https://www.linkdaham.com'
      },
      {
        nome: 'Escala de Estresse Percebido (PSS)',
        autores: ['Cohen, S.', 'Kamarck, T.', 'Mermelstein, R.'],
        anoPublicacao: 1983,
        descritores: ['estresse', 'percepção de estresse', 'avaliação'],
        referencia: 'Cohen, S., Kamarck, T., & Mermelstein, R. (1983). Perceived Stress Scale (PSS). Journal of Health and Social Behavior, 24(4), 385-396.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para medir a percepção de estresse.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede a percepção de estresse e a capacidade do indivíduo de lidar com situações estressantes.',
        link: 'https://www.linkdapss.com'
      },
      {
        nome: 'Escala de Qualidade de Vida (WHOQOL)',
        autores: ['World Health Organization'],
        anoPublicacao: 1998,
        descritores: ['qualidade de vida', 'avaliação', 'bem-estar'],
        referencia: 'World Health Organization. (1998). WHO Quality of Life (WHOQOL) Instrument. World Health Organization.',
        informacoesPsicometricas: 'Validade e confiabilidade para avaliar a qualidade de vida em diversos contextos.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a qualidade de vida geral, incluindo aspectos físicos, psicológicos, sociais e ambientais.',
        link: 'https://www.linkdawhoqol.com'
      },
      {
        nome: 'Escala de Stress Pós-Traumático (PTSD Checklist - PCL)',
        autores: ['Weathers, F. W.', 'Litz, B. T.', 'Herman, D. S.', 'Hodges, J.'], 
        anoPublicacao: 1993,
        descritores: ['transtorno de estresse pós-traumático', 'avaliação', 'sintomas'],
        referencia: 'Weathers, F. W., Litz, B. T., Herman, D. S., & Hodges, J. (1993). PTSD Checklist (PCL). National Center for PTSD.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para avaliar sintomas de estresse pós-traumático.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a gravidade dos sintomas de transtorno de estresse pós-traumático.',
        link: 'https://www.linkdapcl.com'
      },
      {
        nome: 'Escala de Habilidades Sociais (SSRS)',
        autores: ['Gresham, F. M.', 'Elliott, S. N.'],
        anoPublicacao: 1990,
        descritores: ['habilidades sociais', 'avaliação', 'comportamento'],
        referencia: 'Gresham, F. M., & Elliott, S. N. (1990). Social Skills Rating System (SSRS). American Guidance Service.',
        informacoesPsicometricas: 'Alta confiabilidade e validade para medir habilidades sociais e comportamentais.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia as habilidades sociais e o comportamento adaptativo em crianças e adolescentes.',
        link: 'https://www.linkdassrs.com'
      },
      {
        nome: 'Escala de Satisfação com a Vida (SWLS)',
        autores: ['Diener, E.', 'Emmons, R. A.', 'Larsen, R. J.', 'Griffin, S.'],
        anoPublicacao: 1985,
        descritores: ['satisfação com a vida', 'avaliação', 'bem-estar'],
        referencia: 'Diener, E., Emmons, R. A., Larsen, R. J., & Griffin, S. (1985). Satisfaction With Life Scale (SWLS). Journal of Personality Assessment, 49(1), 71-75.',
        informacoesPsicometricas: 'Boa validade e confiabilidade na avaliação da satisfação geral com a vida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a satisfação geral com a vida e o bem-estar subjetivo.',
        link: 'https://www.linkdaswls.com'
      },
      {
        nome: 'Escala de Autoeficácia (GSE)',
        autores: ['Schwarzer, R.', 'Jerusalem, M.'],
        anoPublicacao: 1995,
        descritores: ['autoeficácia', 'avaliação', 'confiança'],
        referencia: 'Schwarzer, R., & Jerusalem, M. (1995). General Self-Efficacy Scale (GSE). In Measures in Health Psychology: A User’s Portfolio. Causal and Control Beliefs.',
        informacoesPsicometricas: 'Alta confiabilidade e validade na avaliação da crença na própria capacidade de enfrentar desafios.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a crença geral do indivíduo em sua capacidade de enfrentar e superar desafios.',
        link: 'https://www.linkdagse.com'
      },
      {
        nome: 'Escala de Impacto dos Sintomas de Ansiedade (ASIS)',
        autores: ['Gordon, J. R.', 'Rosenfield, S.'],
        anoPublicacao: 2004,
        descritores: ['ansiedade', 'impacto dos sintomas', 'avaliação'],
        referencia: 'Gordon, J. R., & Rosenfield, S. (2004). Anxiety Symptom Impact Scale (ASIS). Journal of Anxiety Disorders, 18(3), 223-235.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para medir o impacto dos sintomas de ansiedade na vida cotidiana.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o impacto dos sintomas de ansiedade nas atividades e no funcionamento diário.',
        link: 'https://www.linkdasis.com'
      },
      {
        nome: 'Inventário de Personalidade de Minnesota (MMPI-2)',
        autores: ['Hathaway, S. R.', 'McKinley, J. C.'],
        anoPublicacao: 1989,
        descritores: ['personalidade', 'diagnóstico', 'avaliação'],
        referencia: 'Hathaway, S. R., & McKinley, J. C. (1989). Minnesota Multiphasic Personality Inventory-2 (MMPI-2). University of Minnesota Press.',
        informacoesPsicometricas: 'Extensa validação e confiabilidade para avaliação de traços de personalidade e psicopatologia.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia uma ampla gama de traços de personalidade e psicopatologia, com foco em problemas emocionais e comportamentais.',
        link: 'https://www.linkdammpi.com'
      },
      {
        nome: 'Escala de Estresse de Vida (LES)',
        autores: ['Holmes, T. H.', 'Rahe, R. H.'],
        anoPublicacao: 1967,
        descritores: ['estresse', 'eventos de vida', 'avaliação'],
        referencia: 'Holmes, T. H., & Rahe, R. H. (1967). Life Events Scale (LES). Journal of Psychosomatic Research, 11(2), 213-218.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para medir o impacto de eventos estressantes na vida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o impacto de eventos estressantes na saúde mental e no bem-estar do indivíduo.',
        link: 'https://www.linkdales.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Beck (BSI)',
        autores: ['Beck, A. T.', 'Steer, R. A.', 'Brown, G. K.'],
        anoPublicacao: 1997,
        descritores: ['ideação suicida', 'avaliar risco', 'depressão'],
        referencia: 'Beck, A. T., Steer, R. A., & Brown, G. K. (1997). Beck Scale for Suicide Ideation (BSI). Psychological Assessment, 9(3), 232-241.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação da ideação suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a gravidade da ideação suicida em pacientes com transtornos psicológicos.',
        link: 'https://www.linkdabs.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Columbia (C-SSRS)',
        autores: ['Posner, K.', 'Brown, G. K.', 'Stanley, B.', 'Brent, D. A.'],
        anoPublicacao: 2008,
        descritores: ['ideação suicida', 'avaliação clínica', 'risco suicida'],
        referencia: 'Posner, K., Brown, G. K., Stanley, B., & Brent, D. A. (2008). Columbia-Suicide Severity Rating Scale (C-SSRS). Clinical Trials, 5(1), 1-17.',
        informacoesPsicometricas: 'Validade e confiabilidade robustas para a avaliação da ideação e comportamento suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade e a frequência da ideação suicida, além de comportamentos suicidas.',
        link: 'https://www.linkdacssrs.com'
      },
      {
        nome: 'Inventário de Ideação Suicida (SSI)',
        autores: ['Beck, A. T.', 'Weissman, A.', 'Lester, D.', 'Trexler, L.'],
        anoPublicacao: 1979,
        descritores: ['ideação suicida', 'avaliar risco', 'depressão'],
        referencia: 'Beck, A. T., Weissman, A., Lester, D., & Trexler, L. (1979). Suicidal Ideation Inventory (SSI). Psychological Reports, 45(3), 803-812.',
        informacoesPsicometricas: 'Boa validade e confiabilidade na avaliação de ideação suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Mede a intensidade e a frequência da ideação suicida em indivíduos.',
        link: 'https://www.linkdassi.com'
      },
      {
        nome: 'Escala de Avaliação de Risco de Suicídio (SRS)',
        autores: ['Hawton, K.', 'Goldney, R. D.', 'Peat, S.'],
        anoPublicacao: 1999,
        descritores: ['risco suicida', 'avaliação', 'ideação'],
        referencia: 'Hawton, K., Goldney, R. D., & Peat, S. (1999). Suicide Risk Scale (SRS). Journal of Affective Disorders, 53(3), 161-170.',
        informacoesPsicometricas: 'Validade e confiabilidade para avaliação do risco suicida em diferentes contextos clínicos.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia o risco suicida em pacientes e ajuda a identificar fatores de risco associados.',
        link: 'https://www.linkdasrs.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Cássio (EISC)',
        autores: ['Cássio, F. M.'],
        anoPublicacao: 2005,
        descritores: ['ideação suicida', 'avaliação', 'risco'],
        referencia: 'Cássio, F. M. (2005). Escala de Ideação Suicida de Cássio (EISC). Revista Brasileira de Terapias Cognitivas, 3(2), 121-130.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para a avaliação da ideação suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a intensidade da ideação suicida em adultos e adolescentes.',
        link: 'https://www.linkdaeisc.com'
      },
      {
        nome: 'Escala de Ideação Suicida para Adolescentes (ASI-A)',
        autores: ['Nock, M. K.', 'Miller, A. B.'],
        anoPublicacao: 2007,
        descritores: ['ideação suicida', 'adolescentes', 'avaliação'],
        referencia: 'Nock, M. K., & Miller, A. B. (2007). Adolescent Suicidal Ideation Scale (ASI-A). Journal of Clinical Child and Adolescent Psychology, 36(3), 451-458.',
        informacoesPsicometricas: 'Validade e confiabilidade para avaliação de ideação suicida em adolescentes.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a ideação suicida em adolescentes, com foco em sintomas e comportamentos relacionados.',
        link: 'https://www.linkdasi-a.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Orbach (OSIS)',
        autores: ['Orbach, I.'],
        anoPublicacao: 1999,
        descritores: ['ideação suicida', 'avaliação', 'risco'],
        referencia: 'Orbach, I. (1999). Orbach Suicidal Ideation Scale (OSIS). Psychological Medicine, 29(1), 61-70.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação da ideação suicida em diversos contextos.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a intensidade e a gravidade da ideação suicida, com foco em aspectos emocionais e comportamentais.',
        link: 'https://www.linkdaosis.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Maris (MSI)',
        autores: ['Maris, R. W.'],
        anoPublicacao: 1994,
        descritores: ['ideação suicida', 'avaliação', 'risco'],
        referencia: 'Maris, R. W. (1994). Maris Suicidal Ideation Scale (MSI). Archives of General Psychiatry, 51(10), 843-851.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para avaliação da ideação suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a intensidade da ideação suicida em pacientes.',
        link: 'https://www.linkdamsi.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Brown (BSI)',
        autores: ['Brown, G. K.'],
        anoPublicacao: 2001,
        descritores: ['ideação suicida', 'avaliação', 'risco'],
        referencia: 'Brown, G. K. (2001). Brown Suicidal Ideation Scale (BSI). Journal of Clinical Psychiatry, 62(2), 115-121.',
        informacoesPsicometricas: 'Validade e confiabilidade robustas na avaliação da ideação suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade da ideação suicida, com foco em aspectos emocionais e comportamentais.',
        link: 'https://www.linkdabsib.com'
      },
      {
        nome: 'Escala de Ideação Suicida de Kessler (KSI)',
        autores: ['Kessler, R. C.', 'Moss, A. K.'],
        anoPublicacao: 2002,
        descritores: ['ideação suicida', 'avaliação', 'risco'],
        referencia: 'Kessler, R. C., & Moss, A. K. (2002). Kessler Suicidal Ideation Scale (KSI). Psychological Science, 13(1), 12-18.',
        informacoesPsicometricas: 'Alta validade e confiabilidade para medir a ideação suicida.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a intensidade da ideação suicida, com foco em sintomas e comportamentos.',
        link: 'https://www.linkdaksi.com'
      },
      {
        nome: 'Escala de Avaliação de Transtornos de Ansiedade (HADS)',
        autores: ['Zigmond, A. S.', 'Snaith, R. P.'],
        anoPublicacao: 1983,
        descritores: ['ansiedade', 'transtornos de ansiedade', 'saúde mental'],
        referencia: 'Zigmond, A. S., & Snaith, R. P. (1983). Hospital Anxiety and Depression Scale (HADS). Acta Psychiatrica Scandinavica, 67(6), 361-370.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação de ansiedade e depressão.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a severidade de sintomas de ansiedade e depressão em contextos hospitalares.',
        link: 'https://www.linkdahads.com'
      },
      {
        nome: 'Inventário de Transtorno de Déficit de Atenção e Hiperatividade (ADHD-RS)',
        autores: ['DuPaul, G. J.', 'Power, T. J.', 'Anastopoulos, A. D.', 'Reid, R.'],
        anoPublicacao: 1997,
        descritores: ['déficit de atenção', 'hiperatividade', 'transtorno'],
        referencia: 'DuPaul, G. J., Power, T. J., Anastopoulos, A. D., & Reid, R. (1997). ADHD Rating Scale-IV. Journal of the American Academy of Child & Adolescent Psychiatry, 36(12), 1841-1850.',
        informacoesPsicometricas: 'Validade e confiabilidade robustas na avaliação de sintomas de ADHD.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade dos sintomas de déficit de atenção e hiperatividade em crianças.',
        link: 'https://www.linkdaadhd.com'
      },
      {
        nome: 'Escala de Avaliação de Transtornos Bipolares (YMRS)',
        autores: ['Young, R. C.', 'Biggs, J. T.', 'Ziegler, V. E.', 'Meyer, D. A.'],
        anoPublicacao: 1978,
        descritores: ['transtorno bipolar', 'mania', 'depressão'],
        referencia: 'Young, R. C., Biggs, J. T., Ziegler, V. E., & Meyer, D. A. (1978). Young Mania Rating Scale (YMRS). British Journal of Psychiatry, 133(5), 429-435.',
        informacoesPsicometricas: 'Validade e confiabilidade para medir a gravidade da mania.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a severidade dos sintomas maníacos em pacientes com transtorno bipolar.',
        link: 'https://www.linkdaymrs.com'
      },
      {
        nome: 'Escala de Avaliação de Transtorno Obsessivo-Compulsivo (Y-BOCS)',
        autores: ['Yale, J. L.', 'Brown, A. L.', 'Borkovec, T. D.', 'Miller, M.'],
        anoPublicacao: 1989,
        descritores: ['transtorno obsessivo-compulsivo', 'obsessões', 'compulsões'],
        referencia: 'Yale, J. L., Brown, A. L., Borkovec, T. D., & Miller, M. (1989). Yale-Brown Obsessive Compulsive Scale (Y-BOCS). Archives of General Psychiatry, 46(6), 1001-1006.',
        informacoesPsicometricas: 'Validade e confiabilidade elevadas para medir a gravidade dos sintomas de TOC.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a severidade das obsessões e compulsões em indivíduos com transtorno obsessivo-compulsivo.',
        link: 'https://www.linkdaybocs.com'
      },
      {
        nome: 'Escala de Avaliação de Transtorno de Estresse Pós-Traumático (PTSD)',
        autores: ['Foa, E. B.', 'Tolin, D. F.'],
        anoPublicacao: 2000,
        descritores: ['transtorno de estresse pós-traumático', 'trauma', 'avaliação'],
        referencia: 'Foa, E. B., & Tolin, D. F. (2000). Posttraumatic Stress Disorder Checklist (PCL). Journal of Traumatic Stress, 13(4), 551-556.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação de sintomas de PTSD.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a severidade dos sintomas relacionados ao transtorno de estresse pós-traumático.',
        link: 'https://www.linkdaptsd.com'
      },
      {
        nome: 'Escala de Transtorno de Personalidade Borderline (BPDS)',
        autores: ['Linehan, M. M.'],
        anoPublicacao: 1993,
        descritores: ['transtorno de personalidade borderline', 'instabilidade emocional', 'impulsividade'],
        referencia: 'Linehan, M. M. (1993). Borderline Personality Disorder Scale (BPDS). Journal of Consulting and Clinical Psychology, 61(5), 785-795.',
        informacoesPsicometricas: 'Validade e confiabilidade elevadas na avaliação de sintomas de personalidade borderline.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade dos sintomas associados ao transtorno de personalidade borderline.',
        link: 'https://www.linkdabpds.com'
      },
      {
        nome: 'Escala de Avaliação de Transtorno de Conduta (CDI)',
        autores: ['Forness, S. R.', 'Miller, S.'],
        anoPublicacao: 1986,
        descritores: ['transtorno de conduta', 'comportamento disruptivo', 'avaliação'],
        referencia: 'Forness, S. R., & Miller, S. (1986). Conduct Disorder Inventory (CDI). Journal of Abnormal Child Psychology, 14(3), 391-403.',
        informacoesPsicometricas: 'Validade e confiabilidade adequadas para avaliação de comportamento disruptivo.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a gravidade dos sintomas associados ao transtorno de conduta.',
        link: 'https://www.linkdacdi.com'
      },
      {
        nome: 'Inventário de Transtorno de Personalidade Antissocial (APDI)',
        autores: ['Hare, R. D.'],
        anoPublicacao: 1991,
        descritores: ['transtorno de personalidade antissocial', 'comportamento criminoso', 'avaliação'],
        referencia: 'Hare, R. D. (1991). Antisocial Personality Disorder Inventory (APDI). Journal of Abnormal Psychology, 100(2), 215-220.',
        informacoesPsicometricas: 'Boa validade e confiabilidade para a avaliação de transtorno de personalidade antissocial.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença de características associadas ao transtorno de personalidade antissocial.',
        link: 'https://www.linkdaapdi.com'
      },
      {
        nome: 'Escala de Avaliação de Transtorno de Humor (BDI-II)',
        autores: ['Beck, A. T.', 'Steer, R. A.', 'Brown, G. K.'],
        anoPublicacao: 1996,
        descritores: ['transtorno de humor', 'depressão', 'avaliação'],
        referencia: 'Beck, A. T., Steer, R. A., & Brown, G. K. (1996). Beck Depression Inventory-II (BDI-II). Psychological Assessment, 8(2), 77-100.',
        informacoesPsicometricas: 'Alta validade e confiabilidade na avaliação de sintomas depressivos.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a gravidade dos sintomas depressivos e transtornos de humor.',
        link: 'https://www.linkdabdi.com'
      },
      {
        nome: 'Escala de Avaliação de Transtorno de Personalidade Narcisista (NPI)',
        autores: ['Raskin, R.', 'Hall, C. S.'],
        anoPublicacao: 1979,
        descritores: ['transtorno de personalidade narcisista', 'autoestima', 'avaliação'],
        referencia: 'Raskin, R., & Hall, C. S. (1979). Narcissistic Personality Inventory (NPI). Journal of Personality, 47(4), 625-636.',
        informacoesPsicometricas: 'Validade e confiabilidade para avaliação de traços narcisistas.',
        licenca: 'Uso acadêmico e não comercial permitido.',
        descricao: 'Avalia a presença e a intensidade dos traços de personalidade narcisista.',
        link: 'https://www.linkdanpi.com'
      }
  ];
  